name: tag-release-branch

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
        contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create Release Zip
        run: |
          git archive --format=zip --output=str_view-${GITHUB_REF#refs/tags/}.zip HEAD
          echo "ZIP_FILE=str_view-${GITHUB_REF#refs/tags/}.zip" >> $GITHUB_ENV 

      - name: Create draft release
        run: |
          gh release create "${GITHUB_REF#refs/tags/}" \
            --draft \
            --title "${GITHUB_REF#refs/tags/}" \
            --notes "Release Notes:"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload asset to draft
        run: |
          gh release upload "${GITHUB_REF#refs/tags/}" "${ZIP_FILE}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish release
        run: |
          gh release edit "${GITHUB_REF#refs/tags/}" --draft=false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
